# Generated by Django 2.1.7 on 2019-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_uid', models.CharField(max_length=48, unique=True)),
                ('tree_sp_bg', models.CharField(max_length=128)),
                ('tree_sp_lat', models.CharField(max_length=128)),
                ('tree_height', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tree_altitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tree_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tree_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tree_diameter', models.DecimalField(decimal_places=8, max_digits=12)),
                ('is_decorative', models.BooleanField(default=False)),
                ('is_invasive', models.BooleanField(default=False)),
                ('is_healthy', models.BooleanField(default=True)),
            ],
        ),
    ]
